# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='code',
            field=models.CharField(default='Z001', max_length=32),
            preserve_default=False,
        ),
    ]
