# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_business_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='test',
            field=models.CharField(max_length=32, null=True, verbose_name='测试'),
        ),
        migrations.AlterField(
            model_name='business',
            name='code',
            field=models.CharField(default='Z001', max_length=32, null=True),
        ),
    ]
