# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171013_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='test',
        ),
    ]
